import * as vm from 'vm';
import {
  ScriptBuilder,
  SerializationType,
} from '../../../../src/javascript/runtime/ScriptBuilder';
import { XMLProxy } from '../../../../src/javascript/e4x/XMLProxy';

/**
 * Tests for the getArrayOrXmlLength() utility function generated by ScriptBuilder.
 *
 * This function is injected into every filter/transformer script and handles:
 * - undefined/null → 0
 * - Arrays → .length (number)
 * - Strings → .length (number)
 * - XMLProxy → .length() (function call)
 * - Objects without length → 0
 *
 * We test by generating a script, extracting the utility, and running it in a
 * VM context with various inputs.
 */
describe('ScriptBuilder — getArrayOrXmlLength', () => {
  let getArrayOrXmlLength: (obj: unknown) => number;

  beforeAll(() => {
    // Generate a script that includes the getArrayOrXmlLength function
    const builder = new ScriptBuilder({ transpileE4X: false });
    const script = builder.generateFilterTransformerScript(
      [],
      [],
      SerializationType.RAW,
      SerializationType.RAW,
      false
    );

    // Create a VM context and run the generated script to define the function
    const scope: Record<string, unknown> = {
      connectorMessage: {
        getTransformedData: () => '',
        getProcessedRawData: () => null,
        getRawData: () => '',
      },
      phase: [''],
      msg: undefined,
      tmp: undefined,
      XMLProxy: { create: (s: string) => s },
      channelMap: { containsKey: () => false, get: () => undefined, put: () => {} },
      sourceMap: { containsKey: () => false, get: () => undefined, put: () => {} },
      globalMap: { containsKey: () => false, get: () => undefined, put: () => {} },
      globalChannelMap: { containsKey: () => false, get: () => undefined, put: () => {} },
      configurationMap: { containsKey: () => false, get: () => undefined, put: () => {} },
      responseMap: { containsKey: () => false, get: () => undefined, put: () => {} },
      connectorMap: { containsKey: () => false, get: () => undefined, put: () => {} },
      resultMap: { containsKey: () => false, get: () => undefined, put: () => {} },
      logger: { info: () => {}, error: () => {}, warn: () => {}, debug: () => {} },
      alerts: { sendAlert: () => {} },
    };

    const context = vm.createContext(scope);
    const compiled = new vm.Script(script, { filename: 'getArrayOrXmlLength-test.js' });
    compiled.runInContext(context);

    // Extract the function from the context
    getArrayOrXmlLength = scope['getArrayOrXmlLength'] as (obj: unknown) => number;
  });

  // ---------------------------------------------------------------------------
  // Primitive / edge-case inputs
  // ---------------------------------------------------------------------------
  describe('primitive and edge-case inputs', () => {
    it('returns 0 for undefined', () => {
      expect(getArrayOrXmlLength(undefined)).toBe(0);
    });

    it('returns 0 for null', () => {
      expect(getArrayOrXmlLength(null)).toBe(0);
    });

    it('returns 0 for empty array', () => {
      expect(getArrayOrXmlLength([])).toBe(0);
    });

    it('returns 3 for array with 3 elements', () => {
      expect(getArrayOrXmlLength([1, 2, 3])).toBe(3);
    });

    it('returns 0 for empty string', () => {
      expect(getArrayOrXmlLength('')).toBe(0);
    });

    it('returns 5 for "hello"', () => {
      expect(getArrayOrXmlLength('hello')).toBe(5);
    });

    it('returns 0 for plain object (no length property)', () => {
      expect(getArrayOrXmlLength({})).toBe(0);
    });

    it('returns 0 for number', () => {
      expect(getArrayOrXmlLength(42)).toBe(0);
    });

    it('returns 0 for boolean', () => {
      expect(getArrayOrXmlLength(true)).toBe(0);
    });
  });

  // ---------------------------------------------------------------------------
  // Objects with length property (number)
  // ---------------------------------------------------------------------------
  describe('objects with numeric length property', () => {
    it('returns numeric length from array-like objects', () => {
      const arrayLike = { 0: 'a', 1: 'b', length: 2 };
      expect(getArrayOrXmlLength(arrayLike)).toBe(2);
    });
  });

  // ---------------------------------------------------------------------------
  // Objects with length() method (XMLProxy-like)
  // ---------------------------------------------------------------------------
  describe('objects with length() method', () => {
    it('calls length() method when length is a function', () => {
      const xmlLike = { length: () => 7 };
      expect(getArrayOrXmlLength(xmlLike)).toBe(7);
    });

    it('returns correct count for real XMLProxy with children', () => {
      const xml = XMLProxy.create('<root><item>A</item><item>B</item><item>C</item></root>');
      const items = xml.get('item');
      expect(getArrayOrXmlLength(items)).toBe(3);
    });

    it('returns 1 for XMLProxy root element (single node)', () => {
      const xml = XMLProxy.create('<root><child/></root>');
      expect(getArrayOrXmlLength(xml)).toBe(1);
    });

    it('returns 0 for empty XMLProxy query result', () => {
      const xml = XMLProxy.create('<root><item>A</item></root>');
      const noMatch = xml.get('nonexistent');
      expect(getArrayOrXmlLength(noMatch)).toBe(0);
    });
  });
});
